/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\3框架项目\\项目实战\\vue项目\\UI库\\模板\\fengling-ui\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-34d558ea",
    path: "/components/Card/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-34d558ea").then(next)
    },
  },
  {
    path: "/components/Card/index.html",
    redirect: "/components/Card/"
  },
  {
    name: "v-b8afbb6e",
    path: "/components/Input/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b8afbb6e").then(next)
    },
  },
  {
    path: "/components/Input/index.html",
    redirect: "/components/Input/"
  },
  {
    name: "v-3a0c46ea",
    path: "/components/Button/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3a0c46ea").then(next)
    },
  },
  {
    path: "/components/Button/index.html",
    redirect: "/components/Button/"
  },
  {
    name: "v-a46d13aa",
    path: "/components/Checkbox/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a46d13aa").then(next)
    },
  },
  {
    path: "/components/Checkbox/index.html",
    redirect: "/components/Checkbox/"
  },
  {
    name: "v-455c750b",
    path: "/components/form/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-455c750b").then(next)
    },
  },
  {
    path: "/components/form/index.html",
    redirect: "/components/form/"
  },
  {
    name: "v-d8e00b5c",
    path: "/components/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d8e00b5c").then(next)
    },
  },
  {
    path: "/components/index.html",
    redirect: "/components/"
  },
  {
    name: "v-4ef47f36",
    path: "/components/loading/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4ef47f36").then(next)
    },
  },
  {
    path: "/components/loading/index.html",
    redirect: "/components/loading/"
  },
  {
    name: "v-cafca62a",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cafca62a").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-cc58b46a",
    path: "/components/Switch/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cc58b46a").then(next)
    },
  },
  {
    path: "/components/Switch/index.html",
    redirect: "/components/Switch/"
  },
  {
    name: "v-7f89cd32",
    path: "/components/Radio/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7f89cd32").then(next)
    },
  },
  {
    path: "/components/Radio/index.html",
    redirect: "/components/Radio/"
  },
  {
    name: "v-1e7f3a6a",
    path: "/components/Select/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1e7f3a6a").then(next)
    },
  },
  {
    path: "/components/Select/index.html",
    redirect: "/components/Select/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]