/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/Vue2-FengLing-UI/",
  "headTags": [],
  "pages": [
    {
      "title": "安装",
      "frontmatter": {},
      "regularPath": "/components/",
      "relativePath": "components/index.md",
      "key": "v-0661f6d5",
      "path": "/components/",
      "headers": [
        {
          "level": 2,
          "title": "npm 安装",
          "slug": "npm-安装"
        },
        {
          "level": 2,
          "title": "引入 FengLing",
          "slug": "引入-fengling"
        }
      ],
      "lastUpdated": "2022/7/26 下午3:50:16",
      "lastUpdatedTimestamp": 1658821816000
    },
    {
      "frontmatter": {},
      "regularPath": "/components/form/",
      "relativePath": "components/form/index.md",
      "key": "v-77eae9ce",
      "path": "/components/form/",
      "lastUpdated": "2022/7/6 下午12:24:28",
      "lastUpdatedTimestamp": 1657081468000
    },
    {
      "title": "Button 按钮",
      "frontmatter": {},
      "regularPath": "/components/button/",
      "relativePath": "components/button/index.md",
      "key": "v-66abb864",
      "path": "/components/button/",
      "headers": [
        {
          "level": 2,
          "title": "基础用法",
          "slug": "基础用法"
        },
        {
          "level": 2,
          "title": "自定义颜色属性",
          "slug": "自定义颜色属性"
        },
        {
          "level": 2,
          "title": "禁用状态",
          "slug": "禁用状态"
        },
        {
          "level": 2,
          "title": "文字按钮",
          "slug": "文字按钮"
        },
        {
          "level": 2,
          "title": "图标按钮",
          "slug": "图标按钮"
        },
        {
          "level": 2,
          "title": "按钮组",
          "slug": "按钮组"
        },
        {
          "level": 2,
          "title": "加载中",
          "slug": "加载中"
        },
        {
          "level": 2,
          "title": "不同尺寸",
          "slug": "不同尺寸"
        },
        {
          "level": 2,
          "title": "Props",
          "slug": "props"
        },
        {
          "level": 2,
          "title": "事件",
          "slug": "事件"
        },
        {
          "level": 2,
          "title": "Slots",
          "slug": "slots"
        }
      ],
      "lastUpdated": "2022/7/11 下午1:51:57",
      "lastUpdatedTimestamp": 1657518717000
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "FengLingUI",
        "tagline": "基于Vue2的UI组件库",
        "actionText": "快速上手 →",
        "actionLink": "/components/",
        "features": [
          {
            "title": "简洁易上手",
            "details": "基于element-ui二次开发，简洁易上手。"
          },
          {
            "title": "Vue框架",
            "details": "基于Vue2的组件库供大家参考学习及使用。"
          },
          {
            "title": "高复用",
            "details": "提供多种常用的组件并不断更新。"
          }
        ],
        "footer": "FengLingUI 0.1.1"
      },
      "regularPath": "/",
      "relativePath": "index.md",
      "key": "v-6abbedae",
      "path": "/",
      "lastUpdated": "2022/7/7 下午2:19:46",
      "lastUpdatedTimestamp": 1657174786000
    }
  ],
  "themeConfig": {
    "lastUpdated": "最后一次更新",
    "repo": "TIX007/fengling-ui",
    "editLinks": true,
    "docsDir": "docs",
    "editLinkText": "在 GitHub 上编辑此页",
    "repoLabel": "查看源码",
    "search": true,
    "sidebar": {
      "/components/": [
        {
          "title": "开始",
          "collapsable": true,
          "children": [
            ""
          ]
        },
        {
          "title": "组件",
          "collapsable": true,
          "children": [
            {
              "title": "Button 按钮",
              "path": "/components/button/"
            }
          ]
        }
      ],
      "/": [
        {
          "title": "组件",
          "path": "/components/"
        }
      ]
    },
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "组件",
        "link": "/components/"
      },
      {
        "text": "外链",
        "items": [
          {
            "text": "文档地址",
            "link": "https://github.com/TIX007/Vue2-FengLing-UI"
          },
          {
            "text": "Vue3组件库",
            "link": "https://tix007.github.io/vue3-liuying-ui/"
          }
        ]
      }
    ],
    "smoothScroll": true
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "title": "FengLingUI",
      "description": "基于Vue2的UI组件库",
      "path": "/"
    }
  }
}