/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Button 按钮",
      "frontmatter": {},
      "regularPath": "/components/button/",
      "relativePath": "components/button/index.md",
      "key": "v-66abb864",
      "path": "/components/button/",
      "headers": [
        {
          "level": 2,
          "title": "基础用法",
          "slug": "基础用法"
        },
        {
          "level": 2,
          "title": "禁用状态",
          "slug": "禁用状态"
        },
        {
          "level": 2,
          "title": "文字按钮",
          "slug": "文字按钮"
        },
        {
          "level": 2,
          "title": "图标按钮",
          "slug": "图标按钮"
        },
        {
          "level": 2,
          "title": "按钮组",
          "slug": "按钮组"
        },
        {
          "level": 2,
          "title": "加载中",
          "slug": "加载中"
        },
        {
          "level": 2,
          "title": "不同尺寸",
          "slug": "不同尺寸"
        },
        {
          "level": 2,
          "title": "Attributes",
          "slug": "attributes"
        }
      ]
    },
    {
      "title": "安装",
      "frontmatter": {},
      "regularPath": "/components/",
      "relativePath": "components/index.md",
      "key": "v-0661f6d5",
      "path": "/components/",
      "headers": [
        {
          "level": 2,
          "title": "npm 安装",
          "slug": "npm-安装"
        },
        {
          "level": 2,
          "title": "引入 LiuYing",
          "slug": "引入-liuying"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "Hero 标题",
        "tagline": "Hero 副标题",
        "actionText": "快速上手 →",
        "actionLink": "/components/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "index.md",
      "key": "v-6abbedae",
      "path": "/"
    },
    {
      "frontmatter": {},
      "regularPath": "/components/form/",
      "relativePath": "components/form/index.md",
      "key": "v-77eae9ce",
      "path": "/components/form/"
    }
  ],
  "themeConfig": {
    "search": true,
    "sidebar": {
      "/components/": [
        {
          "title": "开始",
          "collapsable": true,
          "children": [
            ""
          ]
        },
        {
          "title": "组件",
          "collapsable": true,
          "children": [
            {
              "title": "Button 按钮",
              "path": "/components/button/"
            }
          ]
        }
      ],
      "/teacher/": [
        {
          "title": "综合素质",
          "path": "/teacher/ke1/",
          "collapsable": true,
          "children": [
            {
              "title": "大前端",
              "link": "/components/button/"
            },
            {
              "title": "大前端",
              "link": "/components/from/"
            }
          ]
        }
      ],
      "/": [
        {
          "title": "组件啊",
          "path": "/components/"
        },
        {
          "title": "教师证",
          "path": "/teacher/"
        }
      ]
    },
    "nav": [
      {
        "text": "大前端",
        "link": "/components/"
      },
      {
        "text": "教师证",
        "link": "/teacher/"
      },
      {
        "text": "外链",
        "items": [
          {
            "text": "网道",
            "link": "https://wangdoc.com/"
          },
          {
            "text": "VUE",
            "link": "https://cn.vuejs.org/v2/guide/"
          }
        ]
      }
    ],
    "smoothScroll": true
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "title": "FengLingUI",
      "description": "基于vue2的UI组件库",
      "path": "/"
    }
  }
}