name: Auto Deploy # 当前工作流程的名称
on: 
  push: 
    branches: 
      - master # 只要push到master分支，就会触发该工作流程
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 使用别人封装好的的action，用于clone该仓库的源码到工作流中
      - name: Checkout
        uses: actions/checkout@v3
        with:
         lfs: true

      # 在工作流中安装node环境（必需，这样才能在后续工作流程中运行 npm install 等指令，否则会报错）
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14.8.0 # 指定node版本
          
      # 打包代码生成环境
      - name: Build
        run: |
          yarn -v
          npm install # 安装依赖
          npm run docs:build # 打包前端代码到生产环境（目标路径为：server/public）
